name: published Docker container image
on: push                                                  
jobs:                         
  first-job:                           
    name: Docker container image                          
    runs-on: ubuntu-latest                           
    steps: 
      - name: Check-out the repo under $GITHUB_WORKSPACE                               
        uses: actions/checkout@v2  
      
      - name: cowsay   
        uses: venkywarriors/ascii-art-Github-action@master
       
      - name: Show ASCII greeting                             
        uses: mscoutermarsh/ascii-art-action@master     
        with:                               
          text: 'Venkateshwara Rao Doijode'
